"""WishlistItem created

Revision ID: 0002
Revises: 0001
Create Date: 2025-03-22 16:36:32.840713

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist_items',
                    sa.Column('acceptor_id', sa.Integer(), nullable=True),
                    sa.Column('donor_id', sa.Integer(), nullable=True),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('link', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['acceptor_id'], ['users.id'],
                                            name=op.f('fk_wishlist_items_acceptor_id_users')),
                    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], name=op.f('fk_wishlist_items_donor_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_wishlist_items'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_items')
    # ### end Alembic commands ###
