name: Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Analysing the code with pylint
        working-directory: ./src
        run: |
          poetry run pylint $(git ls-files '*.py')

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Create JWT cert files
        run: |
          mkdir -p src/certs
          openssl genrsa -out src/certs/jwt-private.pem 2048
          openssl rsa -in src/certs/jwt-private.pem -outform PEM -pubout -out src/certs/jwt-public.pem

      - name: Run Makefile tests
        working-directory: ./src
        run: make test

  validate-migrations:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_db
          POSTGRES_DB: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Apply Alembic migrations
        run: ENV_TYPE=testing alembic upgrade head

      - name: Check for model/schema mismatch
        run: |
          output=$(ENV_TYPE=testing alembic check 2>&1)
          echo "$output"
      
          if echo "$output" | grep -q "No new upgrade operations detected"; then
            echo "Models and DB schema are in sync."
          else
            echo "Detected schema/model mismatch!"
            exit 1
          fi
