name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Analysing the code with pylint
        working-directory: ./src
        run: |
          poetry run pylint $(git ls-files '*.py')

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Create JWT cert files
        run: |
          mkdir -p src/certs
          openssl genrsa -out src/certs/jwt-private.pem 2048
          openssl rsa -in src/certs/jwt-private.pem -outform PEM -pubout -out src/certs/jwt-public.pem

      - name: Run Makefile tests
        working-directory: ./src
        run: make test

  deploy:
    runs-on: ubuntu-latest
    needs:
      - linter
      - tests

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /${{ secrets.SSH_USER }}/shliwist
            git pull
            echo "${{ secrets.BACKEND_ENV_FILE }}" > src/env/.stable.env
            echo "${{ secrets.DOCKER_COMPOSE_ENV_FILE }}" > .env
            docker compose up -d --build
