name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Set env
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        working-directory: src
        run: |
          curl -sSL https://install.python-poetry.org | python3.12 -
          poetry install

  linter:
    runs-on: ubuntu-latest
    needs:
      - setup

    steps:
      - name: Show repo structure
        run: ls -R

      - name: Analysing the code with pylint
        working-directory: src
        run: |
          poetry run pylint $(git ls-files '*.py')

  tests:
    runs-on: ubuntu-latest
    needs:
      - setup

    steps:
      - name: Show repo structure
        run: ls -R

      - name: Run tests with pytest
        working-directory: src
        run: |
          poetry run pytest

  deploy:
    runs-on: ubuntu-latest
    needs:
      - linter
      - tests

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /${{ secrets.SSH_USER }}/shliwist
            git pull
            echo "${{ secrets.BACKEND_ENV_FILE }}" > src/env/.stable.env
            echo "${{ secrets.DOCKER_COMPOSE_ENV_FILE }}" > .env
            docker compose up -d --build